name: test

on:
  push:
    branches:
      - main
    paths-include:
      - pkg/**
  pull_request:
    branches:
      - main
    paths-include:
      - pkg/**

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version: "1.23"
      - name: Validate
        if: matrix.os == 'ubuntu-22.04'
        run: make validate
      - name: Build
        run: make build
      - name: Run Tests
        run: make test
