name: test

on:
  push:
    branches:
      - main
    paths:
      - pkg/**
      - .github/**
  pull_request:
    branches:
      - main
    paths:
      - pkg/**
      - .github/**

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version: "1.23"
      - name: Validate
        if: matrix.os == 'ubuntu-22.04'
        run: make validate
      - name: Build
        run: make build
      - name: Run Tests
        run: make test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          WORKSPACE_PROVIDER_S3_BUCKET: ${{ secrets.WORKSPACE_PROVIDER_S3_BUCKET }}
          WORKSPACE_PROVIDER_S3_BASE_ENDPOINT: ${{ secrets.WORKSPACE_PROVIDER_S3_BASE_ENDPOINT }}
